name: Deploy to EC2

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@54.244.218.245 << 'EOF'
            set -e
            curl -sL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
            sudo npm install -g pm2
            cd /var/www/back_end
            git reset --hard origin
            git pull
            if pm2 describe app > /dev/null; then
              pm2 restart app
            else
              pm2 start /var/www/back_end/app.js --name app
            fi
          EOF
